#!/usr/bin/env python3
"""Builds results/internal_leaderboard.md from results/history.csv + each run's results.jsonl.

Dev tooling (not part of the submission). For every (algorithm, clarify_py, model, split, dataset)
group in history.csv with >=1 run, computes mean +/- stdev of TDS/nDCG/Pass@1/clarification rate/
over-asking rate/avg cost, builds a task x algorithm pass/fail matrix (most recent run per group),
and reports two diagnostics: universal failures (fail in every algorithm) and the oracle rate
(tasks solved by at least one algorithm -- the ceiling for ensemble/selection strategies).

Usage: uv run python scripts/compare_runs.py [--label-filter SUBSTRING]
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
HISTORY_PATH = REPO_ROOT / "results" / "history.csv"
OUTPUT_PATH = REPO_ROOT / "results" / "internal_leaderboard.md"

METRICS = [
    ("tds", "TDS"),
    ("ndcg", "nDCG"),
    ("pass_at_1", "Pass@1"),
    ("clarification_rate", "Clarification rate"),
    ("over_asking_rate", "Over-asking rate"),
    ("avg_cost_usd", "Avg cost/task"),
]


def read_history() -> list[dict]:
    if not HISTORY_PATH.exists():
        return []
    with HISTORY_PATH.open(newline="") as f:
        return list(csv.DictReader(f))


def group_key(row: dict) -> tuple[str, str, str, str, str]:
    return (row["algorithm"], row["clarify_py"], row["model"], row["split"], row["dataset"])


def mean_std(values: list[float]) -> tuple[float, float]:
    if not values:
        return 0.0, 0.0
    m = statistics.mean(values)
    s = statistics.stdev(values) if len(values) > 1 else 0.0
    return m, s


def load_results_jsonl(run_dir: str) -> list[dict] | None:
    path = REPO_ROOT / run_dir / "results.jsonl"
    if not path.exists():
        return None
    with path.open() as f:
        return [json.loads(line) for line in f if line.strip()]


def fmt(metric: str, mean: float, std: float) -> str:
    if metric == "avg_cost_usd":
        return f"${mean:.6f} +/- {std:.6f}"
    if metric in ("pass_at_1", "clarification_rate", "over_asking_rate"):
        return f"{100 * mean:.2f}% +/- {100 * std:.2f}pp"
    return f"{mean:.4f} +/- {std:.4f}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--label-filter",
        default="",
        help="only include history rows whose run_dir contains this substring",
    )
    args = ap.parse_args()

    rows = read_history()
    if args.label_filter:
        rows = [r for r in rows if args.label_filter in r["run_dir"]]

    groups: dict[tuple, list[dict]] = {}
    for r in rows:
        groups.setdefault(group_key(r), []).append(r)

    lines: list[str] = []
    lines.append("# Internal leaderboard (dev tooling, regenerated by scripts/compare_runs.py)")
    lines.append("")
    lines.append(
        "Aggregates `results/history.csv` into mean +/- stdev per (algorithm, model, split, "
        "dataset) group, plus a task x algorithm pass/fail matrix and two diagnostics. "
        "Temperature is 0.7 by default, so a single run is never evidence -- only trust a "
        "difference between groups that exceeds the stdev shown here."
    )
    lines.append("")
    lines.append("## Summary (mean +/- stdev per group)")
    lines.append("")
    header = ["Algorithm", "clarify_py", "Model", "Split/dataset", "n_runs"] + [
        label for _, label in METRICS
    ]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "---|" * len(header))

    def last_ts(key: tuple) -> str:
        return groups[key][-1]["timestamp"]

    ordered_keys = sorted(groups.keys(), key=last_ts, reverse=True)

    for key in ordered_keys:
        algo, clarify_py, model, split, dataset = key
        grp_rows = groups[key]
        n_runs = len(grp_rows)
        cells = [algo, clarify_py, model, f"{split} ({dataset})", str(n_runs)]
        for metric, _ in METRICS:
            values = [float(r[metric]) for r in grp_rows if r.get(metric) not in (None, "")]
            m, s = mean_std(values)
            cells.append(fmt(metric, m, s))
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("")

    lines.append(
        "## Task x algorithm matrix (most recent run per group; pass=1, fail=0, '-'=no data)"
    )
    lines.append("")

    matrix: dict[str, dict[str, int]] = {}
    algo_labels: list[str] = []
    for key in ordered_keys:
        algo, clarify_py, model, split, dataset = key
        label = f"{algo} ({Path(clarify_py).name})"
        if label in algo_labels:
            continue
        latest_row = groups[key][-1]
        results = load_results_jsonl(latest_row["run_dir"])
        if results is None:
            continue
        algo_labels.append(label)
        for r in results:
            matrix.setdefault(r["task_id"], {})[label] = 1 if r["success"] else 0

    if matrix:
        task_ids = sorted(matrix.keys())
        lines.append("| Task | " + " | ".join(algo_labels) + " |")
        lines.append("|---|" + "---|" * len(algo_labels))
        for tid in task_ids:
            cells = [matrix[tid].get(label, "-") for label in algo_labels]
            lines.append(f"| {tid} | " + " | ".join(str(c) for c in cells) + " |")
        lines.append("")

        present_algos_per_task = {
            tid: [lbl for lbl in algo_labels if lbl in matrix.get(tid, {})] for tid in task_ids
        }
        universal_failures = [
            tid
            for tid in task_ids
            if present_algos_per_task[tid]
            and all(matrix[tid][lbl] == 0 for lbl in present_algos_per_task[tid])
        ]
        oracle_solved = [
            tid
            for tid in task_ids
            if present_algos_per_task[tid]
            and any(matrix[tid][lbl] == 1 for lbl in present_algos_per_task[tid])
        ]
        n_tasks = len(task_ids)
        oracle_pct = (100 * len(oracle_solved) / n_tasks) if n_tasks else 0.0
        lines.append("## Diagnostics")
        lines.append("")
        lines.append(
            f"- **Universal failures** (fail in every algorithm that has data for this task): "
            f"{len(universal_failures)}/{n_tasks} -- "
            f"{', '.join(universal_failures) if universal_failures else '(none)'}"
        )
        lines.append(
            f"- **Oracle rate** (solved by at least one algorithm): {len(oracle_solved)}/{n_tasks} "
            f"({oracle_pct:.2f}%) -- ceiling for any ensemble/selection strategy over the "
            "algorithms in the matrix above."
        )
        lines.append("")
    else:
        lines.append("(no results.jsonl data available yet for any group)")
        lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(
        f"Wrote {OUTPUT_PATH} ({len(ordered_keys)} groups, {len(matrix)} distinct tasks in matrix)"
    )


if __name__ == "__main__":
    main()
